#!/bin/sh

load_modules() {
  # Disable module locking
  /bin/chmod 0666 /sys/module/lsm/parameters/module_locking
  /bin/echo 0 > /sys/module/lsm/parameters/module_locking

  if [ $( cat /proc/modules|grep -o cifs ) != "cifs" ]; then
    /sbin/insmod /usr/local/modules/cifs.ko
  fi
  if [ $( cat /proc/modules|grep -o md4 ) != "md4" ]; then
    /sbin/insmod /usr/local/modules/md4.ko
  fi

  # Enable modules locking
  /bin/echo 1 > /sys/module/lsm/parameters/module_locking
  /bin/chmod 0400 /sys/module/lsm/parameters/module_locking
  /bin/echo "Modules loaded"
}

unload_modules() {
  if [ $( cat /proc/modules|grep -o cifs ) != "cifs" ]; then
    /sbin/rmmod cifs
  fi
  if [ $( cat /proc/modules|grep -o md4 ) != "md4" ]; then
    /sbin/rmmod md4
  fi
  /bin/echo "Modules removed"
}

# Below you can add your samba shares.
# NOTE: - replace username and password with the ones you have.
#       - As it is now the share is mounted with full read write permissions.
#         Change it to your own needs.
#       - Replace server path in this case //10.0.0.13/3000GbXBMC with your own.
#       - Create a directory on a removable drive USB or SD-card on where you can
#         mount your smb share. It doesn't work on ~/Downloads files won't be
#         visible in the Files app from chromeos.
mount_cifs() {
  /bin/mount -t cifs -o username=username,password=password,rw,iocharset=utf8,file_mode=0777,dir_mode=0777 //10.0.0.13/3000GbXBMC /media/removable/UNTITLED/timara
  /bin/echo "Mounted :)"
}
# Add here your unmounts.
umount_cifs() {
  /bin/umount /media/removable/UNTITLED/timara
  /bin/echo "Unmounted..."
}

case "$1" in
  start)
    load_modules
    mount_cifs
    ;;
  stop)
    umount_cifs
    unload_modules
    ;;

  *)
    echo "Usage: $0 {start|stop}"
esac
